### ISSUE TITLE
Open Science Grid -> OSG

### ISSUE THREAD

**Issue by bbockelm** [path-cc/path-cc.github.io#108]
We're doing a small rebranding exercise to make the brand just "OSG" instead of "Open Science Grid (OSG)".

Where we can, please scrub the website - and images - to replace "Open Science Grid" with "OSG".

**Comment by CannonLock** [comment]
@bbockelm Do you know where I can images with the OSG replacement or should I create those?

**Comment by osg-cat** [comment]
I am not aware of any official logos with just “OSG”. I can try to get you some original logo files, though, and you are welcome to modify them. Eventually, it would be good for us to save the new logos in the same place (it’s called DocDB) that the old ones live.

**Comment by bbockelm** [comment]
I use the one here: https://github.com/opensciencegrid/opensciencegrid.github.io/blob/master/assets/images/osglogo-large.png

Think we will have to hand wrangle any accompanying OSG.
